spring.application.name=AiAgentDemo

#
spring.ai.openai.base-url=${OPENAI_BASE_URL:https://open.bigmodel.cn/api/paas/v4}
spring.ai.openai.api-key=${OPENAI_API_KEY:}
spring.ai.openai.chat.options.model=${OPENAI_CHAT_MODEL:glm-4.6}
spring.ai.openai.embedding.options.model=${OPENAI_EMBEDDING_MODEL:embedding-3}
spring.ai.openai.embedding.embeddings-path=/embeddings
spring.ai.openai.chat.completions-path=/chat/completions

# Rerank ????
rag.rerank.path=/rerank
rag.rerank.model=rerank

#spring.ai.openai.base-url=https://idealab.alibaba-inc.com/api/openai
#spring.ai.openai.api-key=
#spring.ai.openai.chat.options.model=qwen3.6-plus
#spring.ai.openai.embedding.options.model=text-embedding-v2


# ?? MCP SDK ?? Streamable HTTP ? SSE ?? 405 ?????SDK ????????????
logging.level.io.modelcontextprotocol.client.LifecycleInitializer=ERROR

# IDEAs ????????????????????????
#ideas.base-url=https://aistudio.alibaba-inc.com/api/aiapp/run
#ideas.apps[0].name=????
#ideas.apps[0].ak=??AK
#ideas.apps[0].app-code=????
#ideas.apps[0].app-version=latest
#ideas.apps[0].description=?????????????????????????????

# MCP Server ??
spring.ai.mcp.server.name=AiAgentDemo-MCP-Server
spring.ai.mcp.server.version=1.0.0
